#!/usr/bin/env python3
"""Generate a 2-color heightmap bookmark from an image.

Writes heightmap.png and bookmark.scad to the output directory.
See CLAUDE.md for the print workflow.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
from PIL import Image, ImageFilter

PX_PER_MM = 3
HOLE_DIAMETER_MM = 4.0
HOLE_FROM_TOP_MM = 7.0


def build_heightmap(
    src: Path,
    width_mm: float,
    height_mm: float,
    levels: int,
    contrast: float,
    blur: float,
    invert: bool,
) -> Image.Image:
    img = Image.open(src).convert("L")

    target_w = max(1, int(round(width_mm * PX_PER_MM)))
    target_h = max(1, int(round(height_mm * PX_PER_MM)))

    img_ratio = img.width / img.height
    target_ratio = target_w / target_h
    if img_ratio > target_ratio:
        new_w = target_w
        new_h = max(1, int(round(target_w / img_ratio)))
    else:
        new_h = target_h
        new_w = max(1, int(round(target_h * img_ratio)))

    img = img.resize((new_w, new_h), Image.LANCZOS)
    canvas = Image.new("L", (target_w, target_h), 0)
    canvas.paste(img, ((target_w - new_w) // 2, (target_h - new_h) // 2))
    img = canvas

    if blur > 0:
        img = img.filter(ImageFilter.GaussianBlur(radius=blur))

    arr = np.asarray(img, dtype=np.float32) / 255.0
    arr = (arr - 0.5) * contrast + 0.5
    arr = np.clip(arr, 0.0, 1.0)

    quantized = np.floor(arr * levels).astype(np.int32)
    quantized = np.clip(quantized, 0, levels - 1)

    if invert:
        quantized = (levels - 1) - quantized

    step = 255 // (levels - 1)
    scaled = (quantized * step).astype(np.uint8)
    return Image.fromarray(scaled, mode="L")


SCAD_TEMPLATE = """\
// Generated by bookmark_heightmap.py
// Single-body bookmark. Print on Bambu X1C with AMS:
//   1. Render (F6), Export STL.
//   2. Import bookmark.stl into BambuStudio.
//   3. Filament 1 = dark, Filament 2 = light.
//   4. Add a filament change at layer {swap_layer}
//      (= base_thickness / layer_height). Below that = dark; above = light.

width          = {width};
height         = {height};
base_thickness = {base};
layer_height   = {layer};
levels         = {levels};
hole_diameter  = {hole_d};
hole_from_top  = {hole_y};

surface_max_z = (levels - 1) * layer_height;
total_max_z   = base_thickness + surface_max_z;

module hole() {{
    translate([0, height/2 - hole_from_top, -1])
        cylinder(h = total_max_z + 2, d = hole_diameter, $fn = 64);
}}

module bookmark() {{
    difference() {{
        union() {{
            translate([-width/2, -height/2, 0])
                cube([width, height, base_thickness]);
            translate([0, 0, base_thickness])
                resize([width, height, surface_max_z])
                    surface(file = "heightmap.png", center = true, convexity = 5);
        }}
        hole();
    }}
}}

bookmark();
"""


def write_scad(
    out: Path,
    width: float,
    height: float,
    base: float,
    layer: float,
    levels: int,
) -> int:
    swap_layer = max(1, round(base / layer))
    content = SCAD_TEMPLATE.format(
        width=width,
        height=height,
        base=base,
        layer=layer,
        levels=levels,
        swap_layer=swap_layer,
        hole_d=HOLE_DIAMETER_MM,
        hole_y=HOLE_FROM_TOP_MM,
    )
    out.write_text(content)
    return swap_layer


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("input", type=Path, help="Source image (any PIL-readable format)")
    p.add_argument("--width", type=float, default=50, help="Bookmark width mm")
    p.add_argument("--height", type=float, default=150, help="Bookmark height mm")
    p.add_argument("--levels", type=int, default=6, help="Tonal levels, 2-8")
    p.add_argument("--layer", type=float, default=0.08, help="Layer height mm")
    p.add_argument("--base", type=float, default=0.8, help="Base thickness mm")
    p.add_argument("--contrast", type=float, default=1.3, help="Contrast boost, >1.0")
    p.add_argument("--blur", type=float, default=0.5, help="Gaussian blur radius px")
    p.add_argument("--invert", action="store_true", help="Flip dark/light mapping")
    p.add_argument("--out", type=Path, default=Path("."), help="Output directory")
    args = p.parse_args()

    if args.levels < 2:
        p.error("--levels must be >= 2")

    args.out.mkdir(parents=True, exist_ok=True)

    hm = build_heightmap(
        args.input,
        args.width,
        args.height,
        args.levels,
        args.contrast,
        args.blur,
        args.invert,
    )
    hm_path = args.out / "heightmap.png"
    hm.save(hm_path)

    scad_path = args.out / "bookmark.scad"
    swap_layer = write_scad(
        scad_path,
        args.width,
        args.height,
        args.base,
        args.layer,
        args.levels,
    )

    print(f"wrote {hm_path}")
    print(f"wrote {scad_path}")
    print(f"BambuStudio: add filament change at layer {swap_layer} "
          f"(dark below, light above)")


if __name__ == "__main__":
    main()
